# Generated by Django 2.0.3 on 2018-05-15 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guides', '0008_auto_20180507_2320'),
        ('scholars', '0015_auto_20180510_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='INTEREST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guides.GROUP')),
            ],
        ),
        migrations.CreateModel(
            name='K_LANGUAGES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LANGUAGE',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='P_STUDENT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.PositiveSmallIntegerField()),
                ('Paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholars.PAPER')),
            ],
        ),
        migrations.CreateModel(
            name='R_STUDENT',
            fields=[
                ('Usn', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Code', models.CharField(max_length=1000)),
                ('Github', models.CharField(max_length=40)),
                ('When', models.DateTimeField()),
                ('CodedIn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.LANGUAGE')),
            ],
        ),
        migrations.CreateModel(
            name='STUDENT',
            fields=[
                ('USN', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('Address', models.CharField(max_length=200)),
                ('Course', models.CharField(max_length=2)),
                ('Year', models.PositiveIntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile', models.CharField(max_length=10)),
                ('Gender', models.CharField(max_length=1)),
                ('Photo', models.ImageField(upload_to='')),
                ('Branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guides.BRANCH')),
            ],
        ),
        migrations.AddField(
            model_name='p_student',
            name='Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.STUDENT'),
        ),
        migrations.AddField(
            model_name='k_languages',
            name='Language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.LANGUAGE'),
        ),
        migrations.AddField(
            model_name='k_languages',
            name='Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.STUDENT'),
        ),
        migrations.AddField(
            model_name='interest',
            name='Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.STUDENT'),
        ),
        migrations.AlterUniqueTogether(
            name='p_student',
            unique_together={('Paper', 'Number')},
        ),
        migrations.AlterUniqueTogether(
            name='k_languages',
            unique_together={('Student', 'Language')},
        ),
        migrations.AlterUniqueTogether(
            name='interest',
            unique_together={('Student', 'Group')},
        ),
    ]
