# Generated by Django 2.0.3 on 2018-05-15 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0008_auto_20180507_2320'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SCORE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rank', models.PositiveSmallIntegerField()),
                ('Guide', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guides.GUIDE')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.STUDENT')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('Student', 'Guide')},
        ),
    ]
