# Generated by Django 2.0.3 on 2018-05-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20180515_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='PassCode',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
