# Generated by Django 2.0.3 on 2018-04-23 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='A_SCHOLAR',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PAPER',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=30)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SCHOLAR',
            fields=[
                ('USN', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('Address', models.CharField(max_length=300)),
                ('Year_of_joining', models.PositiveSmallIntegerField()),
                ('Course_type', models.BooleanField()),
                ('Photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='OPTION',
            fields=[
                ('Option', models.PositiveSmallIntegerField()),
                ('Scholar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='scholars.A_SCHOLAR')),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guides.GROUP')),
                ('Guide', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guides.GUIDE')),
            ],
        ),
        migrations.AddField(
            model_name='scholar',
            name='Counsel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scholars.A_SCHOLAR'),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guides.GROUP'),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guides.GUIDE'),
        ),
        migrations.AddField(
            model_name='paper',
            name='Scholar_USN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scholars.SCHOLAR'),
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('Scholar', 'Option')},
        ),
    ]
