# Generated by Django 2.0.3 on 2018-05-02 07:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scholars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='s', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='scholar',
            name='MailId',
            field=models.EmailField(default='naveen@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Password',
            field=models.CharField(default='123456sS', max_length=15, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
