# Generated by Django 2.0.3 on 2018-05-04 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholars', '0002_auto_20180502_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
