# Generated by Django 2.0.3 on 2018-05-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholars', '0003_auto_20180504_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='MASTERS',
            fields=[
                ('USN', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=25)),
                ('Rank', models.PositiveSmallIntegerField()),
                ('Mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='scholar',
            name='MailId',
        ),
        migrations.RemoveField(
            model_name='scholar',
            name='Password',
        ),
        migrations.AddField(
            model_name='scholar',
            name='Mail',
            field=models.EmailField(default='scholar@uvce.org', max_length=254),
        ),
    ]
