# Generated by Django 2.0.3 on 2018-05-08 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0008_auto_20180507_2320'),
        ('scholars', '0004_auto_20180508_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='masters',
            name='Branch',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='guides.BRANCH'),
        ),
    ]
