# Generated by Django 2.0.3 on 2018-05-08 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholars', '0005_masters_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='masters',
            name='PassKey',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='masters',
            name='Branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='guides.BRANCH'),
        ),
    ]
