# Generated by Django 2.0.3 on 2018-05-08 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholars', '0008_auto_20180508_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsel',
            name='Option',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='Scholar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='scholars.MASTERS'),
        ),
    ]
