# Generated by Django 2.0.3 on 2018-05-08 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0008_auto_20180507_2320'),
        ('scholars', '0011_auto_20180508_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='COUNSEL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Option', models.PositiveSmallIntegerField()),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guides.GROUP')),
                ('Guide', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guides.GUIDE')),
                ('Scholar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scholars.MASTERS')),
            ],
        ),
        migrations.AddField(
            model_name='scholar',
            name='Counsel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='scholars.COUNSEL'),
        ),
        migrations.AlterUniqueTogether(
            name='counsel',
            unique_together={('Scholar', 'Option')},
        ),
    ]
