# Generated by Django 2.0.3 on 2018-05-10 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0008_auto_20180507_2320'),
        ('scholars', '0013_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='COUNT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.PositiveSmallIntegerField()),
                ('Count', models.PositiveSmallIntegerField()),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guides.GROUP')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='count',
            unique_together={('Year', 'Group')},
        ),
    ]
