# Generated by Django 2.0.3 on 2018-05-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholars', '0015_auto_20180510_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='status',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='paper',
            old_name='Scholar_USN',
            new_name='TakenBy',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='link',
        ),
        migrations.AddField(
            model_name='paper',
            name='FinishedOn',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='Pdf',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='paper',
            name='TakenOn',
            field=models.DateTimeField(null=True),
        ),
    ]
