# Generated by Django 2.0.3 on 2018-05-20 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholars', '0016_auto_20180520_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='TakenOn',
            new_name='StartedOn',
        ),
    ]
