# Generated by Django 2.0.3 on 2018-05-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholars', '0017_auto_20180520_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='FinishedOn',
            field=models.DateTimeField(default='2000-01-01 00:00:00'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='StartedOn',
            field=models.DateTimeField(default='2000-01-01 00:00:00'),
        ),
    ]
