# Generated by Django 2.0.3 on 2018-05-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholars', '0020_auto_20180520_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='Number',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='paper',
            unique_together={('Number', 'TakenBy')},
        ),
    ]
