# Generated by Django 2.0.3 on 2018-05-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholars', '0021_auto_20180520_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholar',
            name='PassCode',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
