# Generated by Django 2.0.3 on 2018-05-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholars', '0022_scholar_passcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholar',
            name='Gender',
            field=models.CharField(default='not mentioned', max_length=8),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Phone',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='Course_type',
            field=models.CharField(default='full_time', max_length=10),
        ),
    ]
