# Generated by Django 2.0.3 on 2018-06-03 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholars', '0023_auto_20180529_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholar',
            name='Counsel',
        ),
        migrations.AddField(
            model_name='scholar',
            name='Entrance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='scholars.MASTERS'),
        ),
    ]
