# Generated by Django 2.0.3 on 2018-04-23 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BRANCH',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GROUP',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guides.BRANCH')),
            ],
        ),
        migrations.CreateModel(
            name='GUIDE',
            fields=[
                ('USN', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('DOB', models.DateField()),
                ('Address', models.CharField(max_length=300)),
                ('Mobile', models.IntegerField(max_length=10)),
                ('graduated_year', models.PositiveSmallIntegerField()),
                ('Photo', models.ImageField(upload_to='')),
                ('Branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guides.BRANCH')),
            ],
        ),
        migrations.CreateModel(
            name='UNIVERSITY',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='guide',
            name='University',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guides.UNIVERSITY'),
        ),
    ]
