# Generated by Django 2.0.3 on 2018-04-28 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0002_stream'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='STREAM',
            new_name='TOPIC',
        ),
    ]
