# Generated by Django 2.0.3 on 2018-05-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0004_guide_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='MailId',
            field=models.EmailField(default='guide@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='guide',
            name='Password',
            field=models.CharField(default='123456sS', max_length=15),
        ),
    ]
