# Generated by Django 2.0.3 on 2018-05-07 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0006_sample'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sample',
        ),
    ]
