# Generated by Django 2.0.3 on 2018-05-15 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0010_auto_20180515_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='UserId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
