# Generated by Django 2.0.3 on 2018-05-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0011_auto_20180515_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='MailId',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='PassCode',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
