# Generated by Django 2.0.3 on 2018-06-03 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0012_auto_20180522_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='Branch',
        ),
    ]
