# Generated by Django 2.0.3 on 2018-06-03 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0013_remove_group_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='Branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='guides.BRANCH'),
        ),
    ]
