# Generated by Django 2.0.3 on 2018-06-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0014_group_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='DATES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
    ]
